import {test} from '../../playwrightt/node_modules/@playwright/test'
//import { expect } from '@playwright/test';

test("getbytestId", async({page}) => {

    //this code was generated by the pick locator tool of playwright you can do so by start recording and then interacting with the borwser window
    await page.goto('https://www.saucedemo.com/');
    let user = await page.getByTestId('username')
    await user.fill('standard_user');
    console.log(await user.inputValue() )
    await page.getByTestId('password').click();
    await page.getByTestId('password').fill('secret_sauce');
    await page.getByTestId('login-button').click();

})

test.only("amazon.all", async({page}) =>{
    await page.goto('https://www.amazon.in/s?k=shoes&crid=1JALOQX4P8MXN&sprefix=shoe%2Caps%2C338&ref=nb_sb_noss_2')
    let prods = await page.locator('//a[@class="a-link-normal s-line-clamp-2 puis-line-clamp-3-for-col-4-and-8 s-link-style a-text-normal"]//h2/span');
    let allprods = await prods.all();
    for(const prod of allprods){
        console.log(await prod.innerText());
    }
})

